//
//  FlightListInteractor.swift
//  AircraftApp
//
//  Created by SOTSYS148 on 26/02/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightListInteractorProtocol {
    func callSearchAircraftApi(params:Dictionary<String,Any>,inView: UIView)
}

protocol FlightListDataStore {
    //var name: String { get set }
}

class FlightListInteractor: FlightListInteractorProtocol, FlightListDataStore {
    var presenter: FlightListPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func callSearchAircraftApi(params:Dictionary<String,Any>,inView: UIView) {
        AppSingleton.shared().showSpinner(onView: inView)
        BookingsAPI.searchAircraftPost(iTripType: BookingsAPI.ITripType_searchAircraftPost(rawValue: params["iTripType"] as! String)!, iDepartureId: params["iDepartureId"] as! Int, iDestinationId: params["iDestinationId"] as! Int, iDepartureDate: params["iDepartureDate"] as! Int, iDepartureTime: params["iDepartureTime"] as! Int, iAircraftTypeId: params["iAircraftTypeId"] as! Int, iTripBookingType: BookingsAPI.ITripBookingType_searchAircraftPost(rawValue: params["iTripBookingType"] as! String)!, vDeviceUniqueId: params["vDeviceUniqueId"] as! String, iReturnDate: params["iReturnDate"] as! Int, iReturnTime: params["iReturnTime"] as! Int) { (searchAircraftResponse, error) in
            AppSingleton.shared().removeSpinner()
            if error == nil {
                self.presenter?.getSearchAircraftResponse(response: searchAircraftResponse!)
            } else {
                self.presenter?.getErrorResponse(error: error!)
            }
        }
    }
}
