//
//  FlightListPresenter.swift
//  AircraftApp
//
//  Created by SOTSYS148 on 26/02/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightListPresentationProtocol {
    func callSearchAircraftRequest(params:Dictionary<String,Any>, inView: UIView)
    func getSearchAircraftResponse(response:SearchAircraftResponse)
    func getErrorResponse(error: Error)
}

class FlightListPresenter: FlightListPresentationProtocol {
    weak var viewController: FlightListProtocol?
    var interactor: FlightListInteractorProtocol?
    
    // MARK: Present something
    func callSearchAircraftRequest(params:Dictionary<String,Any>, inView: UIView) {
        self.interactor?.callSearchAircraftApi(params: params, inView: inView)
    }
    
    func getSearchAircraftResponse(response:SearchAircraftResponse) {
        if response.code == APIConstant.ResponseCode.success {
            if response.data != nil {
                self.viewController?.getSearchAircraftResoponse(response: response)
            } else {
                if let view = self.viewController as? UIViewController {
                    let baseDM = BaseModel.init(responseCode: response.code, responseMessage: (response.message)!)
                    view.showAlertView(baseDM)
                }
            }
        } else {
            if let view = self.viewController as? UIViewController {
                let baseDM = BaseModel.init(responseCode: response.code, responseMessage: (response.message)!)
                view.showAlertView(baseDM)
            }
        }
    }
    
    func getErrorResponse(error: Error) {
        self.viewController?.displayAlert(strTitle: APPNAME, strMessage: (error.localizedDescription))
    }
}
