//
//  BookFlightInteractor.swift
//  AircraftApp
//
//  Created by SOTSYS148 on 18/02/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookFlightInteractorProtocol {
    func callAircraftTypeListApi(inView:UIView)
}

protocol BookFlightDataStore {
    //var name: String { get set }
}

class BookFlightInteractor: BookFlightInteractorProtocol, BookFlightDataStore {
    var presenter: BookFlightPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func callAircraftTypeListApi(inView:UIView) {
        AppSingleton.shared().showSpinner(onView: inView)
        BookingsAPI.aircraftTypesListGet { (aircraftTypesListResponse, error) in
            AppSingleton.shared().removeSpinner()
            if error == nil {
                self.presenter?.getAircraftResponse(response: aircraftTypesListResponse!)
            } else {
                self.presenter?.getErrorResponse(error: error!)
            }
        }
    }
}
