//
//  SelectLocationInteractor.swift
//  AircraftApp
//
//  Created by SOTSYS148 on 20/02/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectLocationInteractorProtocol {
    func callAirportListApi(param: Dictionary<String,String>, inView:UIView)
}

protocol SelectLocationDataStore {
    //var name: String { get set }
}

class SelectLocationInteractor: SelectLocationInteractorProtocol, SelectLocationDataStore {
    var presenter: SelectLocationPresentationProtocol?
    //var name: String = ""
    
    // MARK: Do something
    func callAirportListApi(param: Dictionary<String,String>, inView:UIView) {
        AppSingleton.shared().showSpinner(onView: inView)
        BookingsAPI.airportListsPost(vZipcode: param["vZipcode"], vCity: param["vCity"]) { (airportListResponse, error) in
            AppSingleton.shared().removeSpinner()
            if error == nil {
                self.presenter?.getAirportListResponse(response: airportListResponse!)
            } else {
                self.presenter?.getErrorResponse(error: error!)
            }
        }
    }
}
