//
//  SelectLocationPresenter.swift
//  AircraftApp
//
//  Created by SOTSYS148 on 20/02/20.
//  Copyright (c) 2020 SOTSYS203. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectLocationPresentationProtocol {
    func callAirportListRequest(param: Dictionary<String,String>, inView:UIView)
    func getAirportListResponse(response: AirportListResponse)
    func getErrorResponse(error: Error)
}

class SelectLocationPresenter: SelectLocationPresentationProtocol {
    weak var viewController: SelectLocationProtocol?
    var interactor: SelectLocationInteractorProtocol?
    
    // MARK: Present something
    func callAirportListRequest(param: Dictionary<String,String>, inView:UIView) {
        if validateParam(param: param) {
            self.interactor?.callAirportListApi(param: param, inView: inView)
        }
    }
    
    func validateParam(param:Dictionary<String,String>) -> Bool {
        if String(describing: param["vZipcode"]!).isEmpty {
            self.viewController?.displayAlert(strTitle: APPNAME, strMessage: kEnterZipCode)
            return false
        } else if String(describing: param["vZipcode"]!).length != 5 {
            self.viewController?.displayAlert(strTitle: APPNAME, strMessage: kZipcodeRange)
            return false
        }
        
        if String(describing: param["vCity"]!).isEmpty {
            self.viewController?.displayAlert(strTitle: APPNAME, strMessage: "Please Enter City Name")
            return false
        }
        
        return true
    }
    
    func getAirportListResponse(response: AirportListResponse) {
        if response.code == APIConstant.ResponseCode.success {
            if response.data != nil {
                print(response.data)
                self.viewController?.getAirportListResponse(response: response)
            } else{
                if let view = self.viewController as? UIViewController {
                    let baseDM = BaseModel.init(responseCode: response.code, responseMessage: (response.message)!)
                    view.showAlertView(baseDM)
                }
            }
        } else{
            if let view = self.viewController as? UIViewController {
                let baseDM = BaseModel.init(responseCode: response.code, responseMessage: (response.message)!)
                view.showAlertView(baseDM)
            }
        }
    }
    
    func getErrorResponse(error: Error) {
        self.viewController?.displayAlert(strTitle: APPNAME, strMessage: (error.localizedDescription))
    }
}
